### ISSUE TITLE
List Default Android apps

### ISSUE THREAD

**Issue by varlesh** [PapirusDevelopmentTeam/papirus-android-icon-theme#3]
I think we need list Default Android apps... Phone , SMS/MMS, Contacts, Google Play and etc

**Comment by bil-elmoussaoui** [comment]
The activties  and the componentInfo  can be found here http://activities.tundem.com/

**Comment by bil-elmoussaoui** [comment]
Plus, I don't think that we should include everything in the first release, it's just impossible. We must add as must basic apps as possible, and people will report the rest with time ;)
